# Generated by Django 4.0.3 on 2022-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_info',
            name='photo',
            field=models.TextField(),
        ),
    ]
