# Generated by Django 4.0.3 on 2022-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_photo_info_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_info',
            name='created_time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collection_info',
            name='description',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='photo_info',
            name='created_time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='photo_info',
            name='sub_label',
            field=models.TextField(default=''),
        ),
    ]
